name: Parse RSS Feeds

on:
  schedule:
    # Run every hour
    - cron: "*/30 13-22 * * *"
    - cron: "0 23,0-2,12 * * *"
    - cron: "0 3-11/2 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  parse-feeds:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python with Poetry
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.8"
      - name: Install Poetry
        run: |
          pip install poetry

      # Step 3: Install dependencies
      - name: Install dependencies
        run: poetry install

      # Step 4: Download previous cache artifacts if they exist
      - name: Download cache artifacts
        id: download-cache
        uses: actions/download-artifact@v4
        with:
          name: cache-artifacts
          path: cache-artifacts
        continue-on-error: true

      # Step 5: Check if cache exists and create if needed
      - name: Check and create cache
        if: steps.download-cache.outcome == 'failure'
        run: |
          mkdir -p cache
          poetry run python actions/validateCache.py --reconcile
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          SUPABASE_SER_KEY: ${{ secrets.SUPABASE_SER_KEY }}

      # Step 6: Copy artifacts to cache directory if they exist
      - name: Prepare cache directory
        if: steps.download-cache.outcome == 'success'
        run: |
          mkdir -p cache
          cp -r cache-artifacts/* cache/ || true

      # Step 7: Run the feed parser script
      - name: Run feed parser script
        run: poetry run python actions/feedParser.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          SUPABASE_SER_KEY: ${{ secrets.SUPABASE_SER_KEY }}

      # Step 8: Upload cache artifacts
      - name: Upload cache artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cache-artifacts
          path: cache/
          retention-days: 7
