name: Parse RSS Feeds

on:
  schedule:
    # Run every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  parse-feeds:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python with Poetry
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Poetry
        run: |
          pip install poetry
          poetry install

      # Step 3: Install dependencies
      - name: Install dependencies
        run: poetry install

      # Step 4: Run the feed parser script
      - name: Run feed parser script
        run: poetry run python actions/feedParser.py
